### ISSUE TITLE
how to run plumber api + deploy

### ISSUE THREAD

**Issue by singha53-zz** [Zelazny7/reactor#1]
Hi,

How can I launch the R app from the terminal? I am not sure what this statement means: "To test the application can be launched from R, run launchAppDev()."

Also is it possible to deploy using Heroku without using docker?

Sorry, new to web dev :)
A

**Comment by gravesee** [comment]
Hi you can run this command from the command line from the top-level directory of reactor:

`R -e "library(reactor); launchAppDev()"`

This will pass the expression to R and execute it. It should launch your browser and display the simple react app that is connected to R via plumbr.

I wish I could help you with deployment. I, too, am new to webdev and this repository is a collection of what I've learned to get started. If I find out how to deploy to Heroku I'll update the Readme.

**Comment by singha53-zz** [comment]
@Zelazny7 it works! thanks. Didnt know you could put a react app within an r package lol. mind blown. Just incase you are interested: I found another app that use vue on the front end and r on the back-end.
Best,
A

**Comment by gravesee** [comment]
Glad it worked for you. As a person new to web development I would be very interested in a link to the app that uses Vue as well. I have used React in the past and understand it's model but I've heard Vue is great, too.

**Comment by singha53-zz** [comment]
@Zelazny7 sorry! forgot to paste the link: https://github.com/lautiamkok/nuxt-plumber. 
A
